name: Deployment to Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-node-

      - name: Clean install of dependencies
        run: npm ci

      - name: Build
        run: ./node_modules/.bin/webpack --config webpack/build.config.js --env API_HOST=$STAGING_API_HOST --env FIREBASE_API_KEY=$STAGING_FIREBASE_API_KEY --env FIREBASE_AUTH_DOMAIN=$STAGING_FIREBASE_AUTH_DOMAIN --env FIREBASE_DATABASE_URL=$STAGING_FIREBASE_DATABASE_URL --env FIREBASE_PROJECT_ID=$STAGING_FIREBASE_PROJECT_ID

      - name: Minio Deploy
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_STAGING_ENDPOINT }}
          access_key: ${{ secrets.MINIO_STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_STAGING_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_STAGING_BUCKET }}
          source_dir: 'dist'
          target_dir: '/'

      - name: Build Demo
        run: ./node_modules/.bin/webpack --config webpack/build.config.js --env API_HOST=$DEMO_API_HOST --env FIREBASE_API_KEY=$DEMO_FIREBASE_API_KEY --env FIREBASE_AUTH_DOMAIN=$DEMO_FIREBASE_AUTH_DOMAIN --env FIREBASE_DATABASE_URL=$DEMO_FIREBASE_DATABASE_URL --env FIREBASE_PROJECT_ID=$DEMO_FIREBASE_PROJECT_ID

      - name: Minio Deploy Demo
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_STAGING_ENDPOINT }}
          access_key: ${{ secrets.MINIO_STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_STAGING_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_STAGING_DEMO_BUCKET }}
          source_dir: 'dist'
          target_dir: '/'
