name: Deployment to Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Clean install of dependencies
        run: npm ci

      - name: Build
        run: npx webpack --config webpack/build.config.js
        env:
          API_HOST: ${{ secrets.STAGING_API_HOST }}
          FIREBASE_API_KEY: ${{ secrets.STAGING_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.STAGING_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.STAGING_FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.STAGING_FIREBASE_PROJECT_ID }}

      - name: Minio Deploy
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_STAGING_ENDPOINT }}
          access_key: ${{ secrets.MINIO_STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_STAGING_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_STAGING_BUCKET }}
          source_dir: 'dist'
          target_dir: '/'
          insecure: 'true'
